language: c

sudo: true

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - apache2
            - build-essential
            - gcovr
            - gperf
            - lcov
            - valgrind
            - check
            - libsubunit-dev
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - apache2
            - build-essential
            - gcovr
            - gperf
            - lcov
            - valgrind
            - check
            - libsubunit-dev
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - apache2
            - build-essential
            - gcovr
            - gperf
            - lcov
            - valgrind
            - check
            - libsubunit-dev
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - apache2
            - build-essential
            - gcovr
            - gperf
            - lcov
            - valgrind
            - check
            - libsubunit-dev
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - apache2
            - build-essential
            - gcovr
            - gperf
            - lcov
            - valgrind
            - check
            - libsubunit-dev
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - apache2
            - build-essential
            - gcovr
            - gperf
            - lcov
            - valgrind
            - check
            - libsubunit-dev
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - apache2
            - build-essential
            - gcovr
            - gperf
            - lcov
            - valgrind
            - check
            - libsubunit-dev
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ./configure --enable-testing
  - make lib && make test && make memtest
  - make report
